baseURL = "https://fcarp10.page/"
#baseURL = "localhost"
languageCode = "en-us"
title = "Francisco Carpio | Technische UniversitÃ¤t Braunschweig"
theme = "hugo-theme-console"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  custom_css = ["css/custom-style.css"]

  [[params.navlinks]]
  name = "publications/"
  url = "publications/"

  [[params.navlinks]]
  name = "github/"
  url = "https://github.com/fcarp10"

  #[[params.navlinks]]
  #name = "posts/"
  #url = "posts/"
  
